// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Mailer is an autogenerated mock type for the Mailer type
type Mailer struct {
	mock.Mock
}

// SendConfirmation provides a mock function with given fields: email, token
func (_m *Mailer) SendConfirmation(email string, token string) error {
	ret := _m.Called(email, token)

	if len(ret) == 0 {
		panic("no return value specified for SendConfirmation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(email, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendWeatherUpdate provides a mock function with given fields: email, city, weatherInfo
func (_m *Mailer) SendWeatherUpdate(email string, city string, weatherInfo string) error {
	ret := _m.Called(email, city, weatherInfo)

	if len(ret) == 0 {
		panic("no return value specified for SendWeatherUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(email, city, weatherInfo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMailer creates a new instance of Mailer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMailer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mailer {
	mock := &Mailer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
