version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    depends_on:
      - db
    entrypoint: ["/bin/sh", "-c", "/scripts/wait-for-postgres.sh db 5432 ${DB_USER} && migrate -path /migrations -database 'postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable' up"]
    volumes:
      - ./migrations:/migrations
      - ./scripts:/scripts
    env_file:
      - .env

  app:
    build: .
    depends_on:
      - db
      - migrate
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./scripts:/scripts
    command: ["/bin/sh", "-c", "/scripts/wait-for-postgres.sh db 5432 ${DB_USER} && ./weather-api-application"]

volumes:
  db_data:
